version: "2"

services:
  upload:
    image: ${REGISTRY_URL}/pmis-fileupload
    volumes:
    - tmp:/tmp
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    volumes:
    - ngx:/etc/nginx/www
    environment:
    - LOGSPOUT=ignore

  hub:
    environment:
    - LOGSPOUT=ignore
    volumes: 
    - ${SSL_HOME}:/etc/nginx/ssl
    - /etc/letsencrypt:/etc/letsencrypt
    - /tmp:/usr/share/nginx/html
    - ./conf.d:/usr/share/nginx/conf.d