version: "2"

services:
  hub:
    build: hub
    extends: 
      file: common-services.yml
      service: hub
    ports:
    - "80:80"
    - "443:443"
    networks:
    - hub_net

  upload:
    extends: 
      file: common-services.yml
      service: upload
    networks:
    - hub_net

  php:
    extends: 
      file: common-services.yml
      service: php
    networks:
    - hub_net

networks: 
  hub_net:
    external: true

volumes: 
  ngx:
  tmp: