version: "2"

services:
  hub:
    build: hub
    ports:
    - "80:80"
    - "443:443"
    networks:
    - hub_net
    volumes: 
    - ${SSL_HOME}:/etc/nginx/ssl
    - /etc/letsencrypt:/etc/letsencrypt
    - /tmp:/usr/share/nginx/html
    - ./conf.d:/usr/share/nginx/conf.d

  upload:
    extends: 
      file: common-services.yml
      service: upload
    networks:
    - hub_net

  php:
    extends: 
      file: common-services.yml
      service: php
    networks:
    - hub_net

networks: 
  hub_net:
    external: true

volumes: 
  ngx:
  tmp: