version: "2"

services:
  hub:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: hub
    ports:
    - "80:80"
    - "443:443"
    networks:
    - hub_net
    restart: "unless-stopped"

#   upload:
#     extends: 
#       file: common-services.yml
#       service: upload
#     networks:
#     - hub_net
#     restart: "unless-stopped"

#   php:
#     extends: 
#       file: common-services.yml
#       service: php
#     networks:
#     - hub_net
#     restart: "unless-stopped"

networks: 
  hub_net:
    external: true

volumes: 
  ngx:
  tmp:
    external: true