version: "2"

services: 

  nginx:
    container_name: sample-web-srv
    image: nginx:alpine
    volumes: 
    - ./html:/usr/share/nginx/html
    networks: 
      hub_net:
        aliases:
        - sample

  php:
    image: php:5.6-fpm
    volumes:
    - ./html:/usr/share/nginx/html
    networks: 
      hub_net:
        aliases:
        - samplephp

networks: 
  hub_net:
    external: true